#!/bin/bash

{ # this context block is here to prevent TOCTOU when scripting
	if [[ $# -ne 0 ]]; then
		echo $0: error: this script does not take any arguments! >&2
		exit -1
	fi

	# TODO get from env
	BUCKSHOT_SSH_HOSTNAME='buckshot'
	BUCKSHOT_PROJECT_DIR='/home/reuben/Code'

	cd $(dirname $0)

	THIS_FILE=$(basename "$0")

	if [[ -d 'copyback' ]]; then
		rm -rf copyback
	fi

	rsync -avz --delete \
		--exclude='.venv/' \
		--filter='protect .venv/' \
		--exclude='uv.lock' \
		--filter='protect uv.lock' \
		--exclude='.git*' \
		--exclude='__pycache__' \
		--exclude='*.pyc' \
		--exclude='README.md' \
		--exclude="$THIS_FILE" \
		. "$BUCKSHOT_SSH_HOSTNAME:$BUCKSHOT_PROJECT_DIR"

	./pi_util/drop_pi_caches.sh

	echo -e \\nStarting interactive shell...
	ssh -t "$BUCKSHOT_SSH_HOSTNAME" "cd $BUCKSHOT_PROJECT_DIR && mkdir copyback && bash -l" # TODO make safer injection by using pi's env vars

	echo -e \\nCleaning up...
	./pi_util/drop_pi_caches.sh

	if ssh "$BUCKSHOT_SSH_HOSTNAME" "test -d '$BUCKSHOT_PROJECT_DIR/copyback/'"; then
		rsync -avz "$BUCKSHOT_SSH_HOSTNAME:$BUCKSHOT_PROJECT_DIR/copyback/" ./copyback/
	else
		echo -e "\\nNothing to copy back: remote directory '$BUCKSHOT_SSH_HOSTNAME:$BUCKSHOT_PROJECT_DIR/copyback/' does not exist"
	fi

	exit 0
}